#!/usr/bin/env bash
set -e

curl -L https://github.com/OpenWaterAnalytics/EPANET-Matlab-Toolkit/archive/v2.2.0-beta.4.tar.gz | tar xz
cd EPANET-Matlab-Toolkit-2.2.0-beta.4
cd epanet_matlab_toolkit

matlab -nodisplay -r "addpath('$PWD'); savepath"